application: weighty-elf-88907
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# Endpoints handler: this must be /_ah/spi for Endpoints, NOT /_ah/api!
- url: /_ah/spi/.*
  script: helloworld.APPLICATION

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0